### ISSUE TITLE
Add mobile layout

### ISSUE THREAD

**Issue by kidwm** [chewing/chewing.github.com#7]
make site responsive

**Comment by wi1d5ky** [comment]
需要 RWD 的好像只有上面的 nav_bar?

**Comment by kidwm** [comment]
版面順便調整一下也比較好啦

**Comment by wi1d5ky** [comment]
這個網站要用 susy 嗎？
還是跟 http://f2etw.github.io 一樣直接加入 layout.scss 就好了呢？

**Comment by kidwm** [comment]
直接加就行了，單純就好

**Comment by kidwm** [comment]
@wi1d5ky 你忘了加上 <meta> ，記得要在手機上自己先測試過啊

**Comment by wi1d5ky** [comment]
啊... sorry 昨天忘記惹>_____<"
